# Generated by Django 6.0.2 on 2026-04-16 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0001_initial"),
        ("reference", "0002_cropinfo_can_hold_in_field"),
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesevent",
            name="entry_kind",
            field=models.CharField(
                choices=[("plan", "Plan"), ("actual", "Actual")],
                default="actual",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="salesevent",
            name="planning_year",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sales_events",
                to="planning.planningyear",
            ),
        ),
        migrations.AddConstraint(
            model_name="salesevent",
            constraint=models.UniqueConstraint(
                fields=("entry_kind", "channel", "sale_date", "product"),
                name="sales_event_kind_channel_date_product_uniq",
            ),
        ),
    ]
