# Generated by Django 6.0.2 on 2026-04-17 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0002_alter_inventoryledger_options_packbatch_and_more"),
        ("sales", "0002_salesevent_entry_kind_salesevent_planning_year_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesevent",
            name="pack_batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales_events",
                to="operations.packbatch",
            ),
        ),
    ]
