# Generated by Django 5.x migration

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0003_salesevent_pack_batch"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesevent",
            name="drawn_from_return",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resale_draws",
                to="sales.salesevent",
            ),
        ),
    ]
