# Generated by Django 6.0.2 on 2026-04-22 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0005_salesevent_sales_category_and_nullable_channel"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="salesevent",
            options={"ordering": ["sale_date", "channel", "sales_category"]},
        ),
    ]
