# Generated by Django 6.0.2 on 2026-03-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropinfo',
            name='can_hold_in_field',
            field=models.BooleanField(default=False),
        ),
    ]
