# Generated by Django 6.0.2 on 2026-04-17 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference", "0002_cropinfo_can_hold_in_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductRecipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("output_unit", models.CharField(blank=True, max_length=20)),
                ("effective_start", models.DateField(blank=True, null=True)),
                ("effective_end", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipes",
                        to="reference.cropsalesformat",
                    ),
                ),
            ],
            options={
                "ordering": ["product__product_name", "-effective_start", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProductRecipeComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "component_quantity",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("component_unit", models.CharField(max_length=20)),
                (
                    "component_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components",
                        to="reference.productrecipe",
                    ),
                ),
                (
                    "source_crop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recipe_components",
                        to="reference.cropinfo",
                    ),
                ),
                (
                    "source_product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="as_recipe_component",
                        to="reference.cropsalesformat",
                    ),
                ),
            ],
            options={
                "ordering": ["recipe", "sort_order", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="productrecipe",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("product",),
                name="product_recipe_single_active_per_product",
            ),
        ),
    ]
