# Generated by Django 6.0.2 on 2026-04-21 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference", "0003_productrecipe_productrecipecomponent_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Variety",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("supplier", models.CharField(blank=True, max_length=120)),
                ("catalog_number", models.CharField(blank=True, max_length=80)),
                ("source_url", models.URLField(blank=True, max_length=500)),
                ("notes", models.TextField(blank=True)),
                ("scraped_description", models.TextField(blank=True)),
                (
                    "scraped_dtm_days",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "scraped_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("scraped_at", models.DateTimeField(blank=True, null=True)),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="varieties",
                        to="reference.cropinfo",
                    ),
                ),
            ],
            options={
                "ordering": ["crop__name", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("crop", "name"), name="variety_unique_per_crop_name"
                    )
                ],
            },
        ),
    ]
