# Generated by Django 6.0.2 on 2026-04-22 15:05

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference", "0004_variety_seed_order_planting_fk"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Markets", "Markets"),
                            ("Orders", "Orders"),
                            ("CSA", "CSA"),
                        ],
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("allocation_priority", models.PositiveIntegerField(default=10)),
            ],
            options={
                "ordering": ["allocation_priority", "name"],
            },
        ),
        migrations.AddField(
            model_name="saleschannel",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="channels",
                to="reference.salescategory",
            ),
        ),
        migrations.CreateModel(
            name="SalesPlanBucket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("start_week", models.PositiveIntegerField(default=1)),
                ("end_week", models.PositiveIntegerField(default=52)),
                (
                    "weekly_target",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                ("allocation_priority", models.PositiveIntegerField(default=10)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plan_buckets",
                        to="reference.salescategory",
                    ),
                ),
            ],
            options={
                "ordering": ["allocation_priority", "name"],
            },
        ),
        migrations.AddField(
            model_name="saleschannel",
            name="plan_bucket",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="channels",
                to="reference.salesplanbucket",
            ),
        ),
    ]
