# Generated by Django 6.0.2 on 2026-04-24 18:34

import django.db.models.deletion
from decimal import Decimal

from django.db import migrations, models


def seed_yearly_prices_and_refresh_cache(apps, schema_editor):
    """Backfill CropSalesFormatYear from existing CropSalesFormat; cache = latest planning year.

    When no PlanningYear rows exist yet (fresh DB / tests), skip yearly rows and leave
    CropSalesFormat.sale_price as-is until the first import creates planning years.
    """
    CropSalesFormat = apps.get_model("reference", "CropSalesFormat")
    CropSalesFormatYear = apps.get_model("reference", "CropSalesFormatYear")
    PlanningYear = apps.get_model("planning", "PlanningYear")

    years = list(PlanningYear.objects.values_list("year", flat=True).order_by("-year"))
    if not years:
        return

    py = PlanningYear.objects.filter(year=years[0]).first()
    if py is None:
        return

    for csf in CropSalesFormat.objects.all().iterator():
        price = csf.sale_price
        active = csf.is_active
        if price is None:
            price = Decimal("0.00")
        CropSalesFormatYear.objects.update_or_create(
            product=csf,
            planning_year=py,
            defaults={"sale_price": price, "is_active": active},
        )

    for csf in CropSalesFormat.objects.all().iterator():
        latest = (
            CropSalesFormatYear.objects.filter(product_id=csf.pk)
            .select_related("planning_year")
            .order_by("-planning_year__year", "-id")
            .first()
        )
        if latest:
            CropSalesFormat.objects.filter(pk=csf.pk).update(
                sale_price=latest.sale_price,
                is_active=latest.is_active,
            )


def reverse_seed(apps, schema_editor):
    CropSalesFormatYear = apps.get_model("reference", "CropSalesFormatYear")
    CropSalesFormatYear.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_variety_seed_order_planting_fk'),
        ('reference', '0007_cropinfo_fresh_holds_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropsalesformat',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.CreateModel(
            name='CropSalesFormatYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('planning_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crop_sales_format_years', to='planning.planningyear')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearly_prices', to='reference.cropsalesformat')),
            ],
            options={
                'ordering': ['-planning_year__year', 'product__product_name'],
                'constraints': [models.UniqueConstraint(fields=('product', 'planning_year'), name='cropsalesformatyear_unique_product_planning_year')],
            },
        ),
        migrations.RunPython(seed_yearly_prices_and_refresh_cache, reverse_seed),
    ]
