# Generated by Django 6.0.2 on 2026-04-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference", "0009_saleschannel_days_of_week_jsonb"),
    ]

    operations = [
        migrations.AddField(
            model_name="cropbyseason",
            name="sheet_actual_or_planned_weekly_yield_per_bedfoot",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="cropbyseason",
            name="sheet_planned_wtm_weeks",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=7, null=True
            ),
        ),
        migrations.AddField(
            model_name="cropbyseason",
            name="sheet_weekly_yield_forecast",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=10, null=True
            ),
        ),
    ]
