# Generated by Django 6.0.2 on 2026-04-21 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0001_initial"),
        ("reference", "0004_variety_seed_order_planting_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="planting",
            name="variety_obj",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="plantings",
                to="reference.variety",
            ),
        ),
        migrations.CreateModel(
            name="SeedOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "planned_quantity",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("unit", models.CharField(default="ounces", max_length=20)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "planning_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seed_orders",
                        to="planning.planningyear",
                    ),
                ),
                (
                    "variety",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seed_order_lines",
                        to="reference.variety",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "planning_year__year",
                    "variety__crop__name",
                    "variety__name",
                ],
            },
        ),
    ]
