# Generated by Django 6.0.2 on 2026-04-17 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0001_initial"),
        ("reference", "0003_productrecipe_productrecipecomponent_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inventoryledger",
            options={"ordering": ["crop__name", "event_date", "created_at", "id"]},
        ),
        migrations.CreateModel(
            name="PackBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "packed_quantity",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("packed_unit", models.CharField(max_length=20)),
                ("pack_date", models.DateField()),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pack_batches",
                        to="reference.cropsalesformat",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pack_batches",
                        to="reference.productrecipe",
                    ),
                ),
            ],
            options={
                "ordering": ["-pack_date", "-id"],
            },
        ),
        migrations.AddField(
            model_name="packallocation",
            name="pack_batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="allocations",
                to="operations.packbatch",
            ),
        ),
        migrations.CreateModel(
            name="PackBatchComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "consumed_quantity",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("consumed_unit", models.CharField(max_length=20)),
                (
                    "component_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "inventory_ledger_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mix_component_rows",
                        to="operations.inventoryledger",
                    ),
                ),
                (
                    "pack_batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components",
                        to="operations.packbatch",
                    ),
                ),
                (
                    "source_crop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pack_batch_components",
                        to="reference.cropinfo",
                    ),
                ),
                (
                    "source_product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pack_batch_product_components",
                        to="reference.cropsalesformat",
                    ),
                ),
            ],
            options={
                "ordering": ["pack_batch", "id"],
            },
        ),
    ]
